-- Metadata adds optional privacy fields before this checkpoint. Historical
-- rows remain explicitly shared; never infer ownership or import ENV secrets.
CREATE TEMP TABLE venture_connector_upgrade_guard (valid INTEGER NOT NULL CHECK (valid = 1));
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'mail_accounts') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'mail_accounts' AND column_name = 'private_owner_id') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_accounts') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_accounts' AND column_name = 'private_owner_id') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'documents') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'documents' AND column_name = 'private_owner_id') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'integration_connections') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'integration_connections' AND column_name = 'private_owner_id') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_events') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_events' AND column_name = 'subject') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_events') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_events' AND column_name = 'body') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_events') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_events' AND column_name = 'starts_at') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_events') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_events' AND column_name = 'ends_at') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_events') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_events' AND column_name = 'due_at') THEN 1 ELSE 0 END;
INSERT INTO venture_connector_upgrade_guard SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'calendar_events') OR EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'calendar_events' AND column_name = 'status') THEN 1 ELSE 0 END;
DROP TABLE venture_connector_upgrade_guard;
